### ISSUE TITLE
node version requirement, env var cleanup

### ISSUE THREAD

**Issue by phongsi** [terra-money/terraswap-graph#1]
Issue: some of the syntax like optional chaining used in this app requires at least node version 14 and higher [source](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining) This app currently doesnt check for the minimum required version in the [package.js](https://docs.npmjs.com/cli/v7/configuring-npm/package-json#engines).  

Issue: the package-lock.json includes the [dotenv](https://github.com/terra-money/terraswap-graph/blob/master/package-lock.json#L3298) module but doesnt load it anywhere in the app, making a ```.env``` file useless. would be nice to have it required and loaded somewhere or add in the readme that you need ```TERRA_LCD, TERRA_MANTLE, TERRA_CHAIN_ID, optional START_BLOCK_HEIGHT``` passed in the command line.  

Issue: unknown -d option  
```MacBook-Pro:terraswap-graph psi$ npm run migration-run

> terraswap-graph@1.0.0 migration-run
> node --require ts-node/register -r tsconfig-paths/register ./node_modules/typeorm/cli.js migration:run -c migration -d src/orm/migrations

cli.js migration:run

Runs all pending migrations.

Options:
  -h, --help         Show help                                         [boolean]
  -c, --connection   Name of the connection on which run a query.
                                                            [default: "default"]
  -t, --transaction  Indicates if transaction should be used or not for
                     migration run. Enabled by default.     [default: "default"]
  -f, --config       Name of the file with connection configuration.
                                                          [default: "ormconfig"]
  -v, --version      Show version number                               [boolean]

Unknown argument: d
```  

from my understanding this d option is to specify the directory for [generating](https://typeorm.io/#/using-cli/create-a-new-subscriber) a subscriber. It isn't an option for [running](https://github.com/terra-money/terraswap-graph/blob/master/package.json#L12) or [generating](https://github.com/terra-money/terraswap-graph/blob/master/package.json#L10) a migration. Also, the default directory is already defined in the ormconfig file so passing into the npm script is redundant. Removing the -d flag fixes the migration command.

Besides the errors, some refactoring could also be done to also remove the redundancy in the npm script.

**Comment by ALPAC-4** [comment]
Thanks for comment

1. I'll update requirement after the graphql stuff is finish.

2. just added about .envrc 

3. dotenv is requirement of typeorm so it is needed

**Comment by mesyakim** [comment]
migration-run option fixed

**Comment by phongsi** [comment]
Thanks. 😀
